### ISSUE TITLE
Create funtion to follow the person's followers and followings

### ISSUE THREAD

**Issue by prateek-ghanghas** [prateek-ghanghas/product_hunt_growth_tools#4]
Create a function to follow all the followers and following people (should passed i a param). Will use **follow_person_using_person_id** 
in this new funtion in a loop. make sure to stop when the daily following limit is exhausted

**Comment by prateek-ghanghas** [comment]
we create a function with a functionality to follow all the person's followers (take username as param). Will save all the ids came through API in a csv file . Will read the csv file using pandas (dataframe).Then, start following persons using "follow_a_person()" function which take id as a param. Will take a time sleep of 5 seconds between each function call of "follow_a_person()". will take a time sleep of 1 hour whenever following limit exhausts , and save the remaining dataframe back to csv using pandas . Will repeat the process until Dataframe is empty or All the followers are followed.

**Comment by prateek-ghanghas** [comment]
We create two functions , one function will take id , and fetches all the persons  who dont followback that id and unfollow them and then save them in csv file.
The other function will take that csv file as param , to follow all of them .

**Comment by prateek-ghanghas** [comment]
We create two functions , one will fetch all the products launch that day , and the other function will take that list of products and a string  as a  param to make one comment per product .

**Comment by manmohitgrewal1** [comment]
> We create two functions , one function will take id , and fetches all the persons who dont followback that id and unfollow them and then save them in csv file. The other function will take that csv file as param , to follow all of them .

This should be a separate issue. And whenever you write an issue explain point by point like:
Create functionality to unfollow all the users those does not follow back. There will be following 2 functions related to this functionality"
    a. `unfollow_username`: this function will take a user name as a param and then simply unfollow the user
    b. `unfollow_non_followbacks`: this function will iterate over all the "following" accounts and load then into df and then iterate over the df while calling  `unfollow_username`. At last it will save df to csv. (filename should be passed as a param to this function)

**Comment by manmohitgrewal1** [comment]
> We create two functions , one will fetch all the products launch that day , and the other function will take that list of products and a string as a param to make one comment per product .

create a separate issue for this
